wandb_version: 1

n_epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700769001.897152
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.16.0
      8:
      - 5
      13: darwin-arm64
