train:
  model_type: ista
  n_layers: 16
  lr: 0.0001
  weight_decay: 0.0001
  learn_kernel: True
  init_kernel: gaussian
  data_path: ./data/massbank_fixed

test_massbank_fixed:
  data_path: ./data/massbank_fixed
