train:
  model_type: primal_dual
  n_layers: 22
  lr: 0.0001
  weight_decay: 0.0001
  learn_kernel: False
  data_path: ./data/synthetic_identity

test_gaussian:
  data_path: ./data/synthetic_gaussian

test_identity:
  data_path: ./data/synthetic_identity

test_gaussian_heteroscedastic:
  data_path: ./data/synthetic_gaussian_heteroscedastic

test_random_sparse:
  data_path: ./data/synthetic_sparse_random