wandb_version: 1

n_epoch:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 3
lr:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700764887.287633
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
