model_type: half_quadratic
model:
  delta_s_cvx: 0.1
  delta_s_ncvx: 1
  mode: learning_lambda_MM
  number_penalization_cvx: fair
  number_penalization_ncvx: cauchy
  architecture_lambda: lambda_Arch2_overparam
n_layers: 8
lr: 0.01
learn_kernel: False
data_path: ./data/massbank